<?php
namespace WRDSB\Staff\Modules\SchoolData\Model;

class SchoolsList {
    public static function all() {
        $schools = [
            'bci' => 'BCI',
            'chc' => 'CHCI',
            'eci' => 'ECI',
            'eds' => 'EDSS',
            'fhc' => 'FHCI',
            'gci' => 'GCI',
            'gps' => 'GPSS',
            'grc' => 'GRCI',
            'hrh' => 'HHSS',
            'jhs' => 'JHSS',
            'kci' => 'KCI',
            'phs' => 'PHS',
            'jam' => 'SJAM',
            'sss' => 'SSS',
            'wci' => 'WCI',
            'wod' => 'WODSS',

            'ark' => 'A R Kaufman',
            'abe' => 'Abraham Erb',
            'alp' => 'Alpine',
            'ave' => 'Avenue Road',
            'ayr' => 'Ayr',
            'bdn' => 'Baden',
            'blr' => 'Blair Road',
            'bre' => 'Breslau',
            'brp' => 'Bridgeport',
            'bgd' => 'Brigadoon',
            'cdc' => 'Cedar Creek',
            'ced' => 'Cedarbrae',
            'cnc' => 'Centennial (Cambridge)',
            'cnw' => 'Centennial (Waterloo)',
            'ctr' => 'Central',
            'cha' => 'Chalmers Street',
            'chi' => 'Chicopee Hills',
            'cle' => 'Clemens Mill',
            'con' => 'Conestogo',
            'cor' => 'Coronation',
            'coh' => 'Country Hills',
            'crl' => 'Courtland',
            'cre' => 'Crestview',
            'dlf' => 'Elementary Remote Learning 1',
            'dli' => 'Elementary Remote Learning 2',
            'dls' => 'Secondary Remote Learning',
            'doo' => 'Doon',
            'dpk' => 'Driftwood Park',
            'est' => 'Edna Staebler',
            'elg' => 'Elgin Street',
            'elz' => 'Elizabeth Ziegler',
            'emp' => 'Empire',
            'flo' => 'Floradale',
            'fgl' => 'Forest Glen',
            'fhl' => 'Forest Hill',
            'fra' => 'Franklin',
            'gcp' => 'Glencairn',
            'gvc' => 'Grand View (Cambridge)',
            'gvn' => 'Grandview (New Hamburg)',
            'gro' => 'Groh',
            'hes' => 'Hespeler',
            'hig' => 'Highland',
            'hil' => 'Hillcrest',
            'how' => 'Howard Robertson',
            'jfc' => 'J F Carmichael',
            'jwg' => 'J W Gerth',
            'jme' => 'Janet Metcalfe',
            'jst' => 'Jean Steckle',
            'jdp' => 'John Darling',
            'jma' => 'John Mahood',
            'kea' => 'Keatsway',
            'ked' => 'King Edward',
            'lkw' => 'Lackner Woods',
            'lrw' => 'Laurelwood',
            'lau' => 'Laurentian',
            'lbp' => 'Lester B Pearson',
            'lex' => 'Lexington',
            'lnh' => 'Lincoln Heights',
            'lin' => 'Linwood',
            'mcg' => 'MacGregor',
            'mck' => 'Mackenzie King',
            'man' => 'Manchester',
            'mrg' => 'Margaret Avenue',
            'mjp' => 'Mary Johnston',
            'mea' => 'Meadowlane',
            'mil' => 'Millen Woods',
            'mof' => 'Moffat Creek',
            'nam' => 'N A MacEachern',
            'ndd' => 'New Dundee',
            'nlw' => 'Northlake Woods',
            'pkm' => 'Park Manor',
            'pkw' => 'Parkway',
            'pio' => 'Pioneer Park',
            'pre' => 'Preston',
            'pru' => 'Prueter',
            'qel' => 'Queen Elizabeth',
            'qsm' => 'Queensmount',
            'riv' => 'Riverside',
            'roc' => 'Rockway',
            'rmt' => 'Rosemount',
            'rye' => 'Ryerson',
            'sag' => 'Saginaw',
            'shl' => 'Sandhills',
            'snd' => 'Sandowne',
            'she' => 'Sheppard',
            'sil' => 'Silverheights',
            'sab' => 'Sir Adam Beck',
            'smi' => 'Smithson',
            'srg' => 'Southridge',
            'sta' => 'St Andrew\'s',
            'stj' => 'St Jacobs',
            'stn' => 'Stanley Park',
            'stw' => 'Stewart Avenue',
            'sud' => 'Suddaby',
            'sun' => 'Sunnyside',
            'tai' => 'Tait Street',
            'tri' => 'Trillium',
            'vis' => 'Vista Hills',
            'wtt' => 'W T Townshend',
            'wel' => 'Wellesley',
            'wsh' => 'Westheights',
            'wsm' => 'Westmount',
            'wsv' => 'Westvale',
            'wgd' => 'William G Davis',
            'wlm' => 'Williamsburg',
            'wls' => 'Wilson Avenue',
            'wcp' => 'Winston Churchill',
            'wpk' => 'Woodland Park',

            'alc' => 'Alternative Education - Choices',
            'alu' => 'Alternative Education - U-turn',
            'cac' => 'Continuing Education',
            'utr' => 'Rosemount'
        ];

        return $schools;
    }
}





